### PR TITLE
add race method

### PR DESCRIPTION
**Pull request by quanru**
Your job is wonderful, but i need race method which was provided in es6, I hope that you can accept this pull request.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Thanks, looks good to me; I just want to make some minor edits. Could you [give me permission](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)?

**Comment by quanru** [comment]
Is that ok now?

**Comment by RubenVerborgh** [comment]
Yes, thanks; will edit and merge soon.

**Comment by RubenVerborgh** [comment]
@quanru What's happening? There's a new commit and a new package name…

**Comment by quanru** [comment]
@RubenVerborgh I am so sorry, i can't wait you because of some emergency situation yesterday. i reset it now, you can merge it now, sorry again.

**Comment by RubenVerborgh** [comment]
I see, but that should never be a reason to pollute the npm ecosystem with near-identical packages.

Instead, you can do the following in your package.json:

```
{
  "devDependencies": {
    "promiscuous": "quanru/promiscuous",
  }
}
`` `

That way, it will use your fork.

I would strongly recommend to remove promiset from npm to remove confusion.

**Comment by quanru** [comment]
ok, i will try it later.

**Comment by RubenVerborgh** [comment]
Okay, I will wait for your answer before proceeding on this pull request.

**Comment by RubenVerborgh** [comment]
Merged as 3fa5ce78db9765ecb3c0161a2c69b6748af1a1b5.

**Pull request closed without merging**
